### ISSUE TITLE
内存泄露问题

### ISSUE THREAD

**Issue by shifujun** [willz/qqbot#1]
您好！由于打算在VPS上使用，所以对内存占用比较在意。通过简单配置成功运行了您的程序。用的QQ号是新注册的，加入到一个只有2个人的实验群和另一个只有5个人的实验群中。然后没有其他人参与。我只调用了四五次-roll插件，都挺好好使的。刚刚运行的时候，占用了10M内存，这是不错的。然后我就睡觉去了。

我刚刚起床发现，这两个实验群中只有2条新信息，都没有调用机器人。所以机器人一直是闲着的。我用-roll测试了一下，它还在线。但这时它所占用的内存已经上升到122M了。我看了一下我的VPS控制面板，内存使用量的上升是呈线性的。

所以我判断可能是存在内存泄露的问题。不知道您能否快速排查？否则我也得一段代码一段代码测试了。您自己的代码可能您更清楚。谢谢！
![mem](https://f.cloud.github.com/assets/3535204/1993763/15e5d54e-84e0-11e3-80fe-2993da205852.png)

**Comment by willz** [comment]
您好，感谢你对此项目感兴趣。首先，由于python跟java一样是有垃圾回收机制的，除非代码有循环引用的情况，不然是不会有内存泄漏的。然后内存增加的原因可能是1.程序中list,dict等，然后一直往这些容器插入对象，而在使用完后忘了回收。2.正常的python程序行为，之前用过一些长期运行的python程序，内存也是会缓慢增长。
我看了一下代码，并没有发现有循环引用的问题，而list, dict这些容器，应该也是不会有大量对象的。会长期存在的数据结构也就是各个类的**init**()方法里面的self.xxx那些对象，以及可能各个apps的类里存在的static成员，例如apps/gamevote.py里面的state字典。
我这边也没好的环境复现你的情况，你可以参考http://0x55aa.sinaapp.com/%E7%AE%97%E6%B3%95-%E7%BC%96%E7%A8%8B/1075.html 把内存dump下来看看哪部分用的内存多。

**Comment by shifujun** [comment]
我已经参考http://blog.csdn.net/wanghai__/article/details/8299338 大概看了一下。不过也不能确定是哪段代码。

请问据你所知，在这种机器人基本不工作（只在群里呆着，群里没有任何消息）的情况下，有什么代码依然会插入对象呢？
谢谢！

**Comment by willz** [comment]
那只有gamevote那个apps的state dict了，那个gamevote是我自己写的一个插件，用来统计有群里人的状态，但是那个state容器的对象个数不会超过群里成员的个数。你可以试试去掉这个apps。在configs.py把gamevote去掉就可以。
另外在WebQQClient的**init**里面的self.s和self.poll_s也是会一直存在的，这个是requests库的一个session对象，用来发送和接收http请求的，这个如果会泄漏那就是requests库的问题。
其他的都是局部变量，会被垃圾回收的。

**Comment by shifujun** [comment]
好的，谢谢你啊！
